version: '2'
services:
  redis:
    image: redis:3.2.8-alpine
    ports:
    - "6381:6379" 
  postgres:
    image: postgres:9.6.2-alpine
    ports:
    - "5436:5432"
    volumes:
    - ./.db-data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=correx_user
      - POSTGRES_DB=correx_db
      - POSTGRES_PASSWORD=correx_passwd
      - PGDATA=/var/lib/postgresql/data/pgdata
